'use client';
import {useEffect,useState} from 'react';
import {OpsSidebar} from '@/app/components/OpsSidebar';
type Driver={id:string;email:string;display_name:string|null;client:string;is_active:boolean};
export default function TeamPage(){
  const [drivers,setDrivers]=useState<Driver[]>([]),[clients,setClients]=useState<{id:string;name:string}[]>([]),[editable,setEditable]=useState(false),[email,setEmail]=useState(''),[clientId,setClientId]=useState(''),[message,setMessage]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[deliveries,setDeliveries]=useState<{id:string;recipient:string;subject:string;status:string;last_error:string|null}[]>([]);
  async function load(){try{const r=await fetch('/api/ops/team');const b=await r.json();if(!r.ok)throw Error(b.error);setDrivers(b.drivers);setClients(b.clients);setEditable(b.editable);}catch(e){setMessage(String(e));}}
  useEffect(()=>{void load();},[]);
  async function invite(e:React.FormEvent){e.preventDefault();setBusy(true);setLink('');try{const r=await fetch('/api/ops/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,clientId})});const b=await r.json();if(!r.ok)throw Error(b.error);setLink(b.invitationUrl);setMessage(b.note);}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  async function toggle(d:Driver){setBusy(true);try{const r=await fetch('/api/ops/team',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:d.id,active:!d.is_active})});if(!r.ok)throw Error('Account update failed.');await load();}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  async function outbox(send=false){setBusy(true);try{if(send){const r=await fetch('/api/ops/notifications',{method:'POST'});const b=await r.json();if(!r.ok)throw Error(b.error);setMessage(b.disabled?'Email sending is not configured.':`${b.sent} accepted by the email provider; ${b.failed} failed.`);}const r=await fetch('/api/ops/notifications');const b=await r.json();if(!r.ok)throw Error(b.error);setDeliveries(b.items);}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  return <main className="opsShell"><OpsSidebar active="team"/><section className="opsContent"><header className="opsHeader"><div><h1>Drivers & invitations</h1><p>Drivers can send paperwork and see only their own submissions.</p></div></header>{message&&<p role="status">{message}</p>}{editable&&<form className="dashCard" onSubmit={invite}><h2>Invite a driver</h2><label className="field"><span>Email</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Client</span><select required value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Select a client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={busy}>Create invitation</button>{link&&<p><a href={link}>Driver invitation link (48 hours)</a></p>}</form>}<section className="dashCard"><h2>Driver accounts</h2>{drivers.length===0?<p>No driver accounts yet.</p>:<table><thead><tr><th>Driver</th><th>Client</th><th>Access</th></tr></thead><tbody>{drivers.map(d=><tr key={d.id}><td>{d.display_name||d.email}<br/>{d.email}</td><td>{d.client}</td><td>{d.is_active?'Active':'Disabled'} {editable&&<button disabled={busy} onClick={()=>void toggle(d)}>{d.is_active?'Disable':'Enable'}</button>}</td></tr>)}</tbody></table>}</section><section className="dashCard"><h2>Notifications</h2><button disabled={busy} onClick={()=>void outbox()}>Refresh outbox</button> {editable&&<button disabled={busy} onClick={()=>void outbox(true)}>Send queued notifications</button>}<ul>{deliveries.map(d=><li key={d.id}>{d.subject} → {d.recipient}: {d.status}{d.last_error&&` · ${d.last_error}`}</li>)}</ul></section></section></main>;
}
