'use client';
import {useEffect,useRef,type ReactNode} from 'react';
export function OpsIcon({name}:{name:string}) {
  const paths:Record<string,string>={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',funding:'M3 7h18v14H3z M7 7V3h10v4 M3 12h18 M10 16h4',reviews:'M6 3h9l4 4v14H6z M14 3v5h5 M9 12h7 M9 16h5',recovery:'M12 3 2 21h20z M12 9v5 M12 17v.5',debtors:'M3 21V7l9-4 9 4v14 M7 10h1 M12 10h1 M17 10h1 M7 14h1 M12 14h1 M17 14h1 M10 21v-4h4v4',reports:'M3 3v18h18 M7 15l4-5 4 3 6-8',rules:'M13 2 4 14h7l-1 8 10-12h-7z',team:'M16 21v-3c0-3-8-3-8 0v3 M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M19 12c4 0 4 4 4 6',connection:'M2 12h4l3-7 5 14 3-7h5',arrow:'M4 12h16 M15 7l5 5-5 5',check:'M5 12l4 4L19 6'};
  return <svg className="oc-icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.reviews}/></svg>;
}
export function OpsHeader({title,description,actions,children}:{title:string;description:string;actions?:ReactNode;children?:ReactNode}) {return <><div className="oc-topbar"><span>Factor workspace <span aria-hidden="true"> / </span><strong>{title}</strong></span>{children}</div><header className="oc-header"><div><h1>{title}</h1><p>{description}</p></div><div className="oc-actions">{actions}</div></header></>;}
export function OpsPanel({title,description,action,children,className=''}:{title:string;description?:string;action?:ReactNode;children:ReactNode;className?:string}) {return <section className={'oc-panel '+className}><div className="oc-panel-head"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>{children}</section>;}
export function OpsStatus({children,tone='neutral'}:{children:ReactNode;tone?:'good'|'warn'|'bad'|'info'|'neutral'|'suggest'}) {return <span className={'oc-chip '+tone}>{children}</span>;}
export function OpsMetric({label,value,detail,href,critical}:{label:string;value:ReactNode;detail:string;href?:string;critical?:boolean}) {const content=<><span className="oc-metric-label">{label}</span><strong className="oc-metric-value">{value}</strong><small>{detail}</small></>;return href?<a className={'oc-metric '+(critical?'critical':'')} href={href}>{content}</a>:<div className={'oc-metric '+(critical?'critical':'')}>{content}</div>;}
export function OpsNotice({children,tone='info'}:{children:ReactNode;tone?:'info'|'warn'|'bad'}) {return <div className={'oc-notice '+tone} role={tone==='bad'?'alert':undefined}>{children}</div>;}
export function OpsEmpty({children}:{children:ReactNode}) {return <div className="oc-empty">{children}</div>;}
export function OpsDialog({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {const ref=useRef<HTMLDialogElement>(null);const focus=useRef<HTMLElement|null>(null);useEffect(()=>{focus.current=document.activeElement as HTMLElement;const dialog=ref.current;dialog?.showModal();return()=>{dialog?.close();focus.current?.focus();};},[]);return <dialog className="oc-dialog" ref={ref} aria-label={title} onCancel={event=>{event.preventDefault();onClose();}}><div className="oc-dialog-head"><h2>{title}</h2><button className="oc-button" onClick={onClose} aria-label="Close dialog">×</button></div><div className="oc-dialog-body">{children}</div></dialog>;}
export async function opsFetch<T>(url:string):Promise<T> {const res=await fetch(url,{cache:'no-store'});const body=await res.json();if(!res.ok)throw new Error(body.error||'Could not load this data.');return body as T;}
export const opsMoney=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(value);
export const opsTime=(value:string|null|undefined)=>value?new Date(value).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
