'use client';
import {useEffect,useState} from 'react';
import {DemoBadge} from './DemoBadge';
import {OpsPanel,OpsStatus,OpsNotice,OpsEmpty,OpsDialog,opsFetch,opsMoney,opsTime} from './OpsUI';
import {riskCsv,type RiskSignal,type RiskKind,type RiskLevel,type buildRiskMonitor} from '@/lib/risk-monitor';
import styles from './RiskMonitor.module.css';

type RiskData=ReturnType<typeof buildRiskMonitor>&{today:string;fetchedAt:string;demo:boolean;source:{complete:boolean;incompleteReason:string|null;engineAvailable:boolean;engineLimited:boolean;namesLimited:boolean;creditCoverage:string}};
const categories:{key:RiskKind;title:string;unit:string;detail:string;icon:string}[]=[
  {key:'volume',title:'Volume anomalies',unit:'clients',detail:'7-day invoice pace above baseline',icon:'↗'},
  {key:'concentration',title:'Concentration alerts',unit:'exposures / relationships',detail:'Portfolio watch and configured client limits',icon:'◫'},
  {key:'credit',title:'Credit / reserve concerns',unit:'invoice decisions',detail:'Recorded holds and unavailable checks',icon:'◇'},
  {key:'payment',title:'Payment / aging concerns',unit:'debtors',detail:'Slow payment or 90+ invoice-age balance',icon:'◷'}
];
const compact=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(n);
export function RiskMonitor(){
  const [data,setData]=useState<RiskData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[kind,setKind]=useState<RiskKind|'all'>('all'),[level,setLevel]=useState<RiskLevel|'all'>('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<RiskSignal|null>(null);
  async function load(){setLoading(true);setError('');try{setData(await opsFetch<RiskData>('/api/ops/risk'));}catch(e){setError(e instanceof Error?e.message:String(e));setData(null);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const rows=(data?.signals||[]).filter(s=>(kind==='all'||s.kind===kind)&&(level==='all'||s.level===level)&&[s.name,s.trigger,s.scope].join(' ').toLowerCase().includes(query.toLowerCase()));
  function exportCsv(){const blob=new Blob(['\uFEFF'+riskCsv(rows)],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='factorcloud-risk-'+data?.today+'.csv';a.click();URL.revokeObjectURL(url);}
  const chart=data?.daily.slice(-28)||[],maxVolume=Math.max(1,data?.baselineDaily||0,...chart.map(d=>d.count));
  return <div className={styles.root}>
    <div className="oc-toolbar"><span className="oc-small oc-muted">{data?'Snapshot '+data.today+' · refreshed '+opsTime(data.fetchedAt):'Current portfolio risk'}{data?.demo&&<> · <DemoBadge/></>}</span><div className="oc-actions"><button className="oc-button" disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh risk'}</button><button className="oc-button" disabled={!data||!rows.length} onClick={exportCsv}>Export filtered CSV</button></div></div>
    {error&&<OpsNotice tone="bad">{error}</OpsNotice>}
    {!data?<OpsEmpty>{loading?'Loading risk signals…':'Risk data unavailable. Refresh to try again.'}</OpsEmpty>:<>
      {!data.source.complete&&<OpsNotice tone="warn"><strong>Partial portfolio.</strong> {data.source.incompleteReason||'The invoice list could not be read to the end.'} Signal counts and exposure may be understated.</OpsNotice>}
      {!data.source.engineAvailable&&<OpsNotice tone="warn">Credit/reserve evidence and configured client concentration limits are unavailable. Other portfolio watch signals remain visible.</OpsNotice>}
      {data.source.engineLimited&&<OpsNotice tone="warn">Recorded credit/reserve checks cover the latest 500 unresolved decisions; older checks may be omitted.</OpsNotice>}
      <div className={styles.cards}>{categories.map(c=>{const count=data.signals.filter(s=>s.kind===c.key).length,unavailable=c.key==='credit'&&!data.source.engineAvailable;return <button key={c.key} className={styles.card+' '+styles[c.key]} aria-pressed={kind===c.key} onClick={()=>setKind(kind===c.key?'all':c.key)}><span className={styles.cardTitle}><span aria-hidden="true">{c.icon}</span>{c.title}</span><span className={styles.cardValue}>{unavailable?'—':count}<small>{unavailable?'Unavailable':c.unit}</small></span><span className={styles.cardDetail}>{c.detail}</span><span className={styles.cardFoot}>{c.key==='volume'?data.insufficientClients+' clients need more baseline history':c.key==='credit'?'Evidence at decision time':'Current snapshot · no historical delta'}</span></button>;})}</div>
      <div className={styles.charts}>
        <OpsPanel title="Invoice volume" description="Daily invoice-date count · trailing 28 days"><div className="oc-body"><div className={styles.volumeChart} role="img" aria-label="Daily invoice counts with prior 28-day daily baseline; exact values available below."><span className={styles.baseline} style={{bottom:24+(data.baselineDaily/maxVolume)*120}} title={'Baseline '+data.baselineDaily.toFixed(1)+' invoices/day'}/>{chart.map(d=><div className={styles.day} key={d.date} title={d.date+': '+d.count+' invoices'}><i style={{height:Math.max(1,d.count/maxVolume*120)}}/><span>{d.date.slice(8)}</span></div>)}</div><p className={styles.legend}><span>Blue: daily count</span><span>Dashed: {data.baselineDaily.toFixed(1)}/day baseline</span></p><details className="oc-methodology"><summary>View dates and exact counts</summary><div className={styles.dateCounts}>{chart.map(d=><span key={d.date}>{d.date}: <strong>{d.count}</strong></span>)}</div><p>Baseline: prior 28 days, excluding the current 7 days. Dates label the day of month. This measures invoice-date volume, not portal submissions.</p></details></div></OpsPanel>
        <OpsPanel title="Top debtor concentration" description="Share of current open funded A/R"><div className="oc-body">{data.exposure.length?data.exposure.map(e=><div className={styles.barRow} key={e.id}><a className="oc-link" href={'/ops/debtors?debtor='+encodeURIComponent(e.id)}>{e.name}</a><div className="oc-bar"><i style={{width:e.share*100+'%',background:e.share>=.25?'#c74451':e.share>=.15?'#d49b38':undefined}}/></div><strong>{(e.share*100).toFixed(1)}%</strong></div>):<OpsEmpty>No open funded debtor exposure.</OpsEmpty>}<p className="oc-note">Portfolio watch: 15% medium, 25% high. Client/debtor rule limits appear separately in the watchlist.</p></div></OpsPanel>
        <OpsPanel title="Current aging" description="Open funded balance · age from invoice date"><div className="oc-body">{data.aging.map((amount,i)=><div className={styles.barRow} key={i}><span>{['0–30d','31–60d','61–90d','90+d'][i]}</span><div className="oc-bar"><i style={{width:(data.openFunded?amount/data.openFunded*100:0)+'%',background:i===3?'#c74451':undefined}}/></div><strong title={opsMoney(amount)}>{compact(amount)}</strong></div>)}<p className="oc-note">Historical aging and week-over-week changes require saved snapshots. Current balances are shown here.</p></div></OpsPanel>
      </div>
      <OpsPanel title="Risk watchlist" description="Signals with evidence and a clear next review step."><div className={styles.filters}><span>{rows.length} of {data.signals.length} signals · exposure repeats across signal types</span><div className="oc-actions"><select aria-label="Risk severity" value={level} onChange={e=>setLevel(e.target.value as typeof level)}><option value="all">All severities</option><option>High</option><option>Medium</option><option>Unknown</option></select><select aria-label="Risk signal type" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="all">All types</option>{categories.map(c=><option key={c.key} value={c.key}>{c.title}</option>)}</select><input type="search" aria-label="Search risk relationships" placeholder="Search clients, debtors, or triggers" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
        {rows.length?<div className="oc-table-wrap"><table className="oc-table"><thead><tr><th>Severity</th><th>Type / relationship</th><th>Trigger</th><th>Current</th><th>Threshold / basis</th><th className="num">Exposure</th><th>Comparison</th><th>Action</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><OpsStatus tone={s.level==='High'?'bad':s.level==='Medium'?'warn':'neutral'}>{s.level}</OpsStatus></td><td className="oc-identity"><strong>{s.name}</strong><small>{categories.find(c=>c.key===s.kind)?.title}</small><small>{s.scope}</small></td><td className={styles.trigger}>{s.trigger}</td><td>{s.current}</td><td>{s.threshold}</td><td className="num">{s.exposure==null?'Unavailable':compact(s.exposure)}</td><td>{s.comparison||'Snapshot'}{s.daily&&<span className={styles.spark} role="img" aria-label={'Last 7 days: '+s.daily.join(', ')+' invoices'}>{s.daily.map((n,i)=><i key={i} style={{height:Math.max(2,n/Math.max(1,...s.daily!)*26)}}/>)}</span>}</td><td><button className="oc-button" onClick={()=>setSelected(s)}>View details</button></td></tr>)}</tbody></table></div>:<OpsEmpty>{data.signals.length?'No signals match these filters.':'No signals found in the available data at these thresholds.'}</OpsEmpty>}
      </OpsPanel>
      <div className="oc-panel" style={{marginTop:18}}><details className="oc-methodology"><summary>Risk definitions and data coverage</summary><p><strong>Severity:</strong> High = configured concentration breach, recorded financial hold, 25%+ portfolio concentration, 3×+ invoice pace, or any balance aged over 90 days. Medium = 15%+ portfolio concentration, 1.5×+ pace, or payment average above 55 days with at least two paid invoices. Unknown = required recorded checks could not be completed.</p><p>Risk monitoring is read-only. Watch thresholds do not change automation settings or determine purchase eligibility. Aging is invoice age, not due-date delinquency. Exposure is labeled by scope in each detail and should not be summed across alerts.</p><p>{data.coverage.records.toLocaleString()} records loaded; {data.coverage.missingInvoiceDate} missing invoice dates; {data.coverage.assumedBalances} funded records use invoice face value because balance is missing; {data.coverage.missingDebtor} funded records lack debtor identity. {data.source.namesLimited?'Some names could not be resolved within the lookup limit.':''}</p><p>{data.source.creditCoverage} Missing coverage and insufficient baseline history can hide signals; an empty watchlist does not certify that the portfolio has no risk.</p></details></div>
    </>}
    {selected&&<OpsDialog title={selected.name} onClose={()=>setSelected(null)}><OpsStatus tone={selected.level==='High'?'bad':selected.level==='Medium'?'warn':'neutral'}>{selected.level}</OpsStatus><p className="oc-note">{selected.scope}{selected.observedAt?' · recorded '+opsTime(selected.observedAt):' · current snapshot'}</p><OpsNotice tone={selected.level==='High'?'warn':'info'}>{selected.trigger}</OpsNotice><dl className="oc-facts"><div><dt>Current value</dt><dd>{selected.current}</dd></div><div><dt>Threshold</dt><dd>{selected.threshold}</dd></div><div><dt>{selected.exposureLabel}</dt><dd>{selected.exposure==null?'Unavailable':opsMoney(selected.exposure)}</dd></div>{selected.evidence.map((e,i)=><div key={i}><dt>{e.label}</dt><dd>{e.value}</dd></div>)}</dl><h3 className="oc-section-label">Calculation basis</h3><p className="oc-small">{selected.basis}</p><h3 className="oc-section-label">Next review step</h3><p className="oc-small">{selected.nextAction}</p><div className="oc-actions">{selected.links.map(l=><a className="oc-button" key={l.href} href={l.href}>{l.label}</a>)}<button className="oc-button" onClick={()=>setSelected(null)}>Close</button></div></OpsDialog>}
  </div>;
}
