'use client';
import {useEffect,useState} from 'react';
import {OpsSidebar} from '@/app/components/OpsSidebar';
import {DemoBadge} from '@/app/components/DemoBadge';
import {RiskMonitor} from '@/app/components/RiskMonitor';
import {OpsHeader,OpsPanel,OpsMetric,OpsNotice,OpsEmpty,opsFetch,opsMoney} from '@/app/components/OpsUI';
import type {ExposureItem,MonthlyCash,PortfolioKpis} from '@/lib/analytics';
import type {DebtorSummary} from '@/lib/debtors';
type Client={clientId:string;clientName:string;invoiceCount:number;invoiceAmount:number};
type Portfolio={clients:Client[];totals:{invoiceCount:number;clientCount:number};analytics:{today:string;kpis:PortfolioKpis;aging:{totals:number[]};exposure:ExposureItem[];monthlyCash:MonthlyCash[]};demo?:boolean;source:{complete?:boolean;note:string}};
type Debtors={debtors:DebtorSummary[];complete:boolean;incompleteReason:string|null};
const compact=(v:number)=>v>=1000000?'$'+(v/1000000).toFixed(2)+'M':v>=1000?'$'+(v/1000).toFixed(1)+'K':opsMoney(v);
export default function Reports(){
  const [portfolio,setPortfolio]=useState<Portfolio|null>(null),[debtors,setDebtors]=useState<Debtors|null>(null),[loading,setLoading]=useState(true),[errors,setErrors]=useState<string[]>([]),[tab,setTab]=useState<'portfolio'|'risk'|'clients'>('portfolio'),[query,setQuery]=useState('');
  async function load(){setLoading(true);const results=await Promise.allSettled([opsFetch<Portfolio>('/api/ops/clients'),opsFetch<Debtors>('/api/ops/debtors')]);const messages:string[]=[];const a=results[0],b=results[1];if(a.status==='fulfilled')setPortfolio(a.value);else{setPortfolio(null);messages.push('Portfolio: '+a.reason.message);}if(b.status==='fulfilled')setDebtors(b.value);else{setDebtors(null);messages.push('Debtors: '+b.reason.message);}setErrors(messages);setLoading(false);}
  useEffect(()=>{const initial=new URLSearchParams(window.location.search).get('tab');if(initial==='risk'){setTab('risk');setLoading(false);}else{if(initial==='clients')setTab('clients');void load();}},[]);
  function selectTab(next:typeof tab){setTab(next);const url=new URL(window.location.href);url.searchParams.set('tab',next);window.history.replaceState(null,'',url);if(next!=='risk'&&!portfolio&&!loading)void load();}
  const exposure=new Map(portfolio?.analytics.exposure.map(x=>[x.id,x])),clients=(portfolio?.clients||[]).slice().sort((a,b)=>(exposure.get(b.clientId)?.value||0)-(exposure.get(a.clientId)?.value||0)).filter(c=>c.clientName.toLowerCase().includes(query.toLowerCase()));
  const kpis=portfolio?.analytics.kpis,cash=portfolio?.analytics.monthlyCash.slice(-6)||[],maxCash=Math.max(1,...cash.flatMap(x=>[x.advanced,x.collected])),aging=portfolio?.analytics.aging.totals||[];
  function clientTable(){return <div className="oc-table-wrap"><table className="oc-table"><thead><tr><th>Client</th><th className="num">Open funded A/R</th><th className="num">Exposure share</th><th className="num">Loaded invoice value</th><th className="num">Invoice count</th></tr></thead><tbody>{clients.map(client=>{const e=exposure.get(client.clientId);return <tr key={client.clientId}><td><a className="oc-link" href={'/ops/clients/'+encodeURIComponent(client.clientId)}>{client.clientName}</a></td><td className="num">{e?opsMoney(e.value):'—'}</td><td className="num">{e?(e.share*100).toFixed(1)+'%':'—'}</td><td className="num">{opsMoney(client.invoiceAmount)}</td><td className="num">{client.invoiceCount.toLocaleString()}</td></tr>;})}</tbody></table>{!clients.length&&<OpsEmpty>No matching client records.</OpsEmpty>}</div>;}
  return <main className="opsShell"><OpsSidebar active="reports"/><section className="opsContent"><OpsHeader title={tab==='risk'?'Risk Monitor':'Reports'} description={tab==='risk'?'Current signals and exposures that deserve a closer look.':'Portfolio intelligence with explicit periods and metric definitions.'} actions={tab!=='risk'&&<button className="oc-button" disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh data'}</button>}>{portfolio?.demo&&<DemoBadge/>}</OpsHeader>
    {errors.map(error=><OpsNotice key={error} tone="bad">{error}</OpsNotice>)}{portfolio?.source.complete===false&&<OpsNotice tone="warn"><strong>Partial portfolio.</strong> {portfolio.source.note}</OpsNotice>}{debtors&&!debtors.complete&&<OpsNotice tone="warn"><strong>Partial debtor portfolio.</strong> {debtors.incompleteReason}</OpsNotice>}
    <div className="oc-tabs" role="tablist" aria-label="Report section">{(['portfolio','risk','clients'] as const).map(key=><button className="oc-tab" role="tab" key={key} aria-selected={tab===key} onClick={()=>selectTab(key)}>{key==='portfolio'?'Portfolio':key==='risk'?'Risk':'Clients'}{key==='clients'&&portfolio&&<span>{portfolio.clients.length}</span>}</button>)}</div>
    {tab==='risk'?<RiskMonitor/>:!portfolio?<OpsEmpty>{loading?'Loading portfolio reporting…':'Portfolio reporting unavailable.'}</OpsEmpty>:<>

      <div className="oc-toolbar"><span className="oc-small oc-muted">As of {portfolio.analytics.today} · {portfolio.totals.invoiceCount.toLocaleString()} loaded records</span><span className="oc-small oc-muted">Periods shown per measure</span></div>
      {tab==='portfolio'&&kpis&&<><div className="oc-metrics five"><OpsMetric label="Open funded A/R" value={compact(kpis.openBalance)} detail={kpis.openCount+' invoices · snapshot'}/><OpsMetric label="Advances · 30d" value={compact(kpis.fundedLast30)} detail="Recorded advance amounts"/><OpsMetric label="Paid invoice value · 30d" value={compact(kpis.collectedLast30)} detail="Face value of paid invoices"/><OpsMetric label="Fees on paid invoices · 30d" value={compact(kpis.feesLast30)} detail="Recorded purchase fees"/><OpsMetric label="Avg days to pay · 90d" value={kpis.dsoLast90==null?'—':kpis.dsoLast90.toFixed(1)+'d'} detail="Amount-weighted paid cohort"/></div>
        <div className="oc-stack"><div className="oc-two"><OpsPanel title="Funding and payment activity" description="Monthly advances vs paid invoice face value"><div className="oc-body"><div className="oc-months" role="img" aria-label="Monthly recorded advances and paid invoice face value; exact values in the table below.">{cash.map(month=><div key={month.key} title={month.key+': advances '+opsMoney(month.advanced)+', paid invoice value '+opsMoney(month.collected)}><i style={{height:month.advanced/maxCash*145}}/><i className="paid" style={{height:month.collected/maxCash*145}}/><span>{month.label}</span></div>)}</div><div className="oc-legend"><span>Blue: advances</span><span>Gray: paid invoice value</span></div><details className="oc-methodology"><summary>View exact monthly values</summary><table className="oc-table"><thead><tr><th>Month</th><th className="num">Advances</th><th className="num">Paid invoice value</th></tr></thead><tbody>{cash.map(month=><tr key={month.key}><td>{month.key}</td><td className="num">{opsMoney(month.advanced)}</td><td className="num">{opsMoney(month.collected)}</td></tr>)}</tbody></table></details></div></OpsPanel>
        <OpsPanel title="Open A/R aging" description="Days from invoice date; not days past due"><div className="oc-body">{aging.map((value,i)=><div className="oc-figure-row" key={i}><span>{['0–30d','31–60d','61–90d','90+d'][i]}</span><div className="oc-bar"><i style={{width:(kpis.openBalance?value/kpis.openBalance*100:0)+'%',background:i===3?'#a73544':undefined}}/></div><strong className="oc-num">{opsMoney(value)}</strong></div>)}<p className="oc-note">{opsMoney(aging[3]||0)} aged 90+ days · {kpis.openBalance?((aging[3]||0)/kpis.openBalance*100).toFixed(1):'0'}% of open funded A/R</p></div></OpsPanel></div>
        <div className="oc-two"><OpsPanel title="Client exposure concentration" description="Share of open funded A/R" action={<button className="oc-link" onClick={()=>setTab('clients')}>All clients →</button>}>{portfolio.analytics.exposure.slice(0,4).map(e=><a className="oc-exposure" href={'/ops/clients/'+encodeURIComponent(e.id)} key={e.id}><div><strong>{e.name}</strong><strong className="oc-num">{opsMoney(e.value)}</strong></div><small>{(e.share*100).toFixed(1)}% of open funded A/R · {e.invoiceCount} open invoices</small><div className="oc-bar"><i style={{width:e.share*100+'%'}}/></div></a>)}</OpsPanel>
        <OpsPanel title="Largest debtor exposures" description="Open funded balances" action={<a className="oc-link" href="/ops/debtors">Debtor risk →</a>}>{debtors?debtors.debtors.slice().sort((a,b)=>b.openBalance-a.openBalance).slice(0,4).map(d=><a className="oc-exposure" href="/ops/debtors" key={d.debtorId}><div><strong>{d.name}</strong><strong className="oc-num">{opsMoney(d.openBalance)}</strong></div><small>{(d.share*100).toFixed(1)}% of open funded A/R · {d.clientCount} exposed clients</small><div className="oc-bar"><i style={{width:d.share*100+'%'}}/></div></a>):<OpsEmpty>Debtor reporting unavailable.</OpsEmpty>}</OpsPanel></div></div>
      </>}
      {tab==='clients'&&<div className="oc-toolbar"><input type="search" aria-label="Search client portfolio" placeholder="Search clients" value={query} onChange={e=>setQuery(e.target.value)}/></div>}
      <div style={{marginTop:18}}><OpsPanel title="Client portfolio" description="Open exposure and loaded volume are separate measures.">{clientTable()}</OpsPanel></div>
      <div className="oc-panel" style={{marginTop:18}}><details className="oc-methodology"><summary>Metric definitions and data limitations</summary><p><strong>Paid invoice value</strong> sums invoice face value by recorded paid date; it is not a ledger of cash receipts or partial collections.</p><p><strong>Average days to pay</strong> is the amount-weighted invoice-to-payment time for the 90-day paid cohort. It is not conventional balance-based DSO.</p><p><strong>Aging</strong> uses invoice date. Due-date delinquency requires a separate calculation.</p><p><strong>Client exposure share</strong> uses open funded A/R. Loaded invoice value includes the loaded history and is not open exposure.</p><p><strong>Retrieval coverage:</strong> {portfolio.source.note} Complete retrieval does not guarantee coverage of financial fields; missing advance, paid-date, balance, or fee fields may understate those measures.</p></details></div>
    </>}
  </section></main>;
}
