'use client';
import {useEffect,useState} from 'react';
import {OpsSidebar} from '@/app/components/OpsSidebar';
import {OpsHeader,OpsPanel,OpsMetric,OpsNotice,OpsStatus,OpsEmpty,OpsDialog,opsFetch,opsMoney,opsTime} from '@/app/components/OpsUI';
import {modeLabels,runLabel,type FundingData} from '@/lib/operations-view';
import type {EngineRun} from '@/lib/funding-engine';
const lanes=[['decision','Needs a click'],['suggestions','Suggestions'],['exceptions','Failures / unresolved'],['funded','Funded']] as const;
type Lane=typeof lanes[number][0];
export default function FundingCenter() {
  const [data,setData]=useState<FundingData|null>(null),[lane,setLane]=useState<Lane>('decision'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<EngineRun|null>(null),[ack,setAck]=useState(false),[busy,setBusy]=useState(false);
  useEffect(()=>{const value=new URLSearchParams(window.location.search).get('lane');if(lanes.some(([key])=>key===value))setLane(value as Lane);},[]);
  useEffect(()=>{let current=true;setLoading(true);setData(null);setError('');setQuery('');opsFetch<FundingData>('/api/ops/funding?lane='+lane).then(body=>{if(current){setData(body);const id=new URLSearchParams(window.location.search).get('run');const run=body.runs.find(r=>r.id===id);if(run)setSelected(run);}}).catch(err=>{if(current)setError(err.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[lane]);
  async function refresh(more=false){setLoading(true);setError('');try{const cursor=more&&data?.next?'&before='+encodeURIComponent(data.next.createdAt)+'&beforeId='+encodeURIComponent(data.next.id):'';const body=await opsFetch<FundingData>('/api/ops/funding?lane='+lane+cursor);setData(previous=>({...body,runs:more?[...(previous?.runs||[]),...body.runs]:body.runs}));}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setLoading(false);}}
  async function act(){if(!selected)return;setBusy(true);setError('');try{const action=selected.state==='APPROVED'?'fund':'approve';const res=await fetch('/api/ops/funding/'+encodeURIComponent(selected.id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const body=await res.json();if(!res.ok)throw new Error(body.detail||body.error||'The operation did not complete.');setMessage(body.detail||'Operation completed.');setSelected(null);await refresh();}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setBusy(false);}}
  const summary=data?.summary,rows=(data?.runs||[]).filter(r=>([r.invoiceNumber,r.clientName,r.factorCloudInvoiceId,r.detail,...r.reasons].join(' ')).toLowerCase().includes(query.toLowerCase()));
  const unresolved=(run:EngineRun)=>run.state==='FUNDING'||['CHECKING','SENDING','UNKNOWN'].includes(run.approvalStatus||'');
  const selectedAction=selected&&(selected.state==='APPROVED'||selected.state==='SUGGESTED'||selected.state==='FAILED')&&!unresolved(selected);
  return <main className="opsShell"><OpsSidebar active="funding"/><section className="opsContent"><OpsHeader title="Funding Center" description="Understand the decision, the blocker, and the next action." actions={<><a className="oc-button" href="/ops/rules">Automation Rules</a><button className="oc-button" disabled={loading||busy} onClick={()=>void refresh()}>{loading?'Refreshing…':'Refresh'}</button></>}>{data?.available&&<OpsStatus tone="info">{modeLabels[data.mode]}</OpsStatus>}</OpsHeader>
    {error&&<OpsNotice tone="bad">{error}</OpsNotice>}{message&&<OpsNotice>{message}</OpsNotice>}
    {data&&!data.available&&<OpsNotice tone="warn"><strong>Funding automation unavailable.</strong> {data.note}</OpsNotice>}
    {loading&&!data?<OpsEmpty>Loading funding decisions…</OpsEmpty>:data?.available&&<>
      <div className="oc-metrics"><OpsMetric label="Approved · needs funding" value={summary?.approved??'—'} detail={summary?opsMoney(summary.approvedAmount)+' invoice value':'Count unavailable'}/><OpsMetric label="Suggestions" value={summary?.suggested??'—'} detail="Approval has not been executed"/><OpsMetric label="Failures / unresolved" value={summary?summary.failed+summary.uncertain:'—'} detail="Separate failures from uncertain results" critical={Boolean(summary&&(summary.failed+summary.uncertain))}/><OpsMetric label="Auto-funded today" value={summary?.autoToday??'—'} detail={summary?opsMoney(summary.autoTodayAmount)+' invoice value · '+summary.timeZone:'Count unavailable'}/></div>
      <div className="oc-tabs" role="tablist" aria-label="Funding lane">{lanes.map(([key,label])=><button className="oc-tab" role="tab" aria-selected={lane===key} key={key} disabled={loading||busy} onClick={()=>setLane(key)}>{label}<span>{summary?(key==='decision'?summary.approved:key==='suggestions'?summary.suggested:key==='exceptions'?summary.failed+summary.uncertain:summary.funded):'—'}</span></button>)}<button className="oc-tab" disabled title="The current data does not distinguish confirmed in-progress funding from an unknown result.">In progress · unavailable</button></div>
      <div className="oc-toolbar"><input type="search" aria-label="Search loaded funding decisions" placeholder="Search loaded invoices, clients, or reasons" value={query} onChange={e=>setQuery(e.target.value)}/><span className="oc-small oc-muted">{rows.length} matching loaded decisions · {opsMoney(rows.reduce((sum,r)=>sum+r.amount,0))} invoice value</span></div>
      <OpsPanel title={lanes.find(([key])=>key===lane)![1]} description={lane==='decision'?'Approved invoices awaiting a deliberate funding decision.':lane==='suggestions'?'Recorded suggestions; a fresh approval decision still needs a person.':lane==='exceptions'?'An uncertain result requires reconciliation before another operation.':'Completed engine funding records.'}>
        {rows.length?<div className="oc-table-wrap"><table className="oc-table"><thead><tr><th>Invoice / client</th><th>Debtor</th><th>Status & reason</th><th className="num">Invoice value</th><th>Next action</th></tr></thead><tbody>{rows.map(run=><tr key={run.id}><td className="oc-identity"><strong>{run.invoiceNumber||run.factorCloudInvoiceId.slice(0,8)}</strong><small>{run.clientName||'Client not named'}</small></td><td className="oc-muted">Not available</td><td><OpsStatus tone={unresolved(run)||run.state==='FAILED'?'bad':run.state==='FUNDED'?'good':run.state==='SUGGESTED'?'suggest':'info'}>{unresolved(run)?'Reconciliation required':runLabel(run)}</OpsStatus><div className="oc-reason">{run.reasons[0]||run.detail||'All recorded checks passed.'}</div></td><td className="num"><strong>{opsMoney(run.amount)}</strong></td><td>{unresolved(run)?<a className="oc-button" href="/ops/recovery">Open Recovery</a>:<button className="oc-button" disabled={busy} onClick={()=>{setAck(false);setSelected(run);}}>{run.state==='APPROVED'?'Review funding':run.state==='FUNDED'?'View record':'Review decision'}</button>}</td></tr>)}</tbody></table></div>:<OpsEmpty>{query?'No loaded decisions match this search.':'No records in this lane.'}</OpsEmpty>}
      </OpsPanel>
      {data.next&&<p><button className="oc-button" disabled={loading||busy} onClick={()=>void refresh(true)}>{loading?'Loading…':'Load more decisions'}</button></p>}
      <p className="oc-note">Counts cover all runs; the table loads 100 records at a time. Search applies to loaded records. Invoice value is not the final cash disbursement. Debtor identity is not supplied by the current run projection.</p>
      {Boolean(summary?.review)&&<OpsNotice>{summary!.review} engine decision{summary!.review===1?'':'s'} remain blocked at approval. <a href="/ops/reviews">Open Paperwork Review</a></OpsNotice>}
    </>}
    {selected&&<OpsDialog title={(selected.state==='APPROVED'?'Review funding · ':'Review decision · ')+(selected.invoiceNumber||selected.factorCloudInvoiceId.slice(0,8))} onClose={()=>{if(!busy)setSelected(null);}}><dl className="oc-facts"><div><dt>Client</dt><dd>{selected.clientName||'Not named'}</dd></div><div><dt>Invoice value</dt><dd>{opsMoney(selected.amount)}</dd></div><div><dt>Actual disbursement</dt><dd>Not supplied in this view</dd></div><div><dt>Payment type</dt><dd>{selected.paymentType||'Not recorded'}</dd></div><div><dt>Recorded decision mode</dt><dd>{selected.mode}</dd></div><div><dt>Recorded at</dt><dd>{opsTime(selected.createdAt)}</dd></div></dl><div className="oc-section-label">Recorded rule results</div>{selected.rules.map(rule=><div className="oc-check" key={rule.id}><OpsStatus tone={rule.status==='PASS'?'good':rule.status==='REVIEW'||rule.status==='UNKNOWN'?'bad':rule.status==='HOLD'?'warn':'neutral'}>{rule.status}</OpsStatus><strong>{rule.label}</strong><p>{rule.detail}</p></div>)}
      {selectedAction&&<><OpsNotice tone="warn">{selected.state==='APPROVED'?'Confirming submits the funding operation to FactorCloud.':'Approval re-checks current rules and may also fund automatically if Auto-fund is active when it executes.'} Verify the final disbursement and funding instructions in FactorCloud; the invoice value above is not a cash quote.</OpsNotice><label className="oc-rule-toggle"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} disabled={busy}/>I verified the financial details and understand this action.</label></>}
      {error&&<OpsNotice tone="bad">{error}</OpsNotice>}<div className="oc-actions"><button className="oc-button" disabled={busy} onClick={()=>setSelected(null)}>Close</button>{selectedAction&&<button className="oc-button primary" disabled={busy||!ack||!data?.canAct} onClick={()=>void act()}>{busy?'Executing…':selected.state==='APPROVED'?'Confirm funding':'Confirm approval'}</button>}</div>{selectedAction&&!data?.canAct&&<p className="oc-note">Only a Factor Admin can execute this financial action.</p>}
    </OpsDialog>}
  </section></main>;
}
