'use client';
import {useEffect,useState} from 'react';
import {OpsSidebar} from '@/app/components/OpsSidebar';
import {OpsHeader,OpsPanel,OpsMetric,OpsNotice,OpsStatus,OpsEmpty,OpsDialog,OpsSync,opsFetch,opsMoney,opsTime} from '@/app/components/OpsUI';
import {modeLabels,runLabel,type FundingData} from '@/lib/operations-view';
import type {Batch,EngineRun} from '@/lib/funding-engine';
const lanes=[['decision','Needs a click'],['suggestions','Suggestions'],['exceptions','Failures / unresolved'],['funded','Funded']] as const;
type Lane=typeof lanes[number][0];
export default function FundingCenter() {
  const [data,setData]=useState<FundingData|null>(null),[lane,setLane]=useState<Lane>('decision'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<EngineRun|null>(null),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[batch,setBatch]=useState<Batch|null|'loading'|'error'>(null);
  useEffect(()=>{const value=new URLSearchParams(window.location.search).get('lane');if(lanes.some(([key])=>key===value))setLane(value as Lane);},[]);
  useEffect(()=>{let current=true;setLoading(true);setData(null);setError('');setQuery('');opsFetch<FundingData>('/api/ops/funding?lane='+lane).then(body=>{if(current){setData(body);const id=new URLSearchParams(window.location.search).get('run');const run=body.runs.find(r=>r.id===id);if(run)setSelected(run);}}).catch(err=>{if(current)setError(err.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[lane]);
  async function refresh(more=false,force=false){setLoading(true);setError('');try{const cursor=more&&data?.next?'&before='+encodeURIComponent(data.next.createdAt)+'&beforeId='+encodeURIComponent(data.next.id):'';const body=await opsFetch<FundingData>('/api/ops/funding?lane='+lane+cursor+(force?'&refresh=1':''));setData(previous=>({...body,runs:more?[...(previous?.runs||[]),...body.runs]:body.runs}));}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setLoading(false);}}
  useEffect(()=>{setBatch(null);if(!selected||selected.state!=='APPROVED')return;let current=true;setBatch('loading');opsFetch<{batch:Batch|null}>('/api/ops/funding/'+encodeURIComponent(selected.id)).then(body=>{if(current)setBatch(body.batch);}).catch(()=>{if(current)setBatch('error');});return()=>{current=false;};},[selected]);
  const heldForClick=(run:EngineRun)=>run.state==='SUGGESTED'&&run.mode==='fund';
  async function act(){if(!selected)return;setBusy(true);setError('');try{const action=selected.state==='APPROVED'||heldForClick(selected)?'fund':'approve';const res=await fetch('/api/ops/funding/'+encodeURIComponent(selected.id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const body=await res.json();if(!res.ok)throw new Error(body.detail||body.error||'The operation did not complete.');setMessage(body.detail||'Operation completed.');setSelected(null);await refresh();}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setBusy(false);}}
  const summary=data?.summary,rows=(data?.runs||[]).filter(r=>([r.invoiceNumber,r.clientName,r.factorCloudInvoiceId,r.detail,...r.reasons].join(' ')).toLowerCase().includes(query.toLowerCase()));
  const unresolved=(run:EngineRun)=>run.state==='FUNDING'||['CHECKING','SENDING','UNKNOWN'].includes(run.approvalStatus||'');
  const selectedAction=selected&&(selected.state==='APPROVED'||selected.state==='SUGGESTED'||selected.state==='FAILED')&&!unresolved(selected);
  return <main className="opsShell"><OpsSidebar active="funding"/><section className="opsContent"><OpsHeader title="Funding Center" description="Every invoice the automation decided on: what it did, why, and what's left for you." actions={<><a className="oc-button" href="/ops/rules">Automation Rules</a><button className="oc-button" disabled={loading||busy} onClick={()=>void refresh(false,true)}>{loading?'Refreshing…':'Refresh'}</button></>}>{data?.available&&<OpsStatus tone="info">{modeLabels[data.mode]}</OpsStatus>}</OpsHeader>
    {error&&<OpsNotice tone="bad">{error}</OpsNotice>}{message&&<OpsNotice>{message}</OpsNotice>}<OpsSync sync={data?.sync}/>
    {data&&!data.available&&<OpsNotice tone="warn"><strong>Funding automation unavailable.</strong> {data.note}</OpsNotice>}
    {loading&&!data?<OpsEmpty>Loading funding decisions…</OpsEmpty>:data?.available&&<>
      <div className="oc-metrics"><OpsMetric label="Needs a click" value={summary?.approved??'—'} detail={summary?opsMoney(summary.approvedAmount)+' invoice value':'Count unavailable'}/><OpsMetric label="Suggestions" value={summary?.suggested??'—'} detail="Clients on suggest-only"/><OpsMetric label="Failures / unresolved" value={summary?summary.failed+summary.uncertain:'—'} detail="FactorCloud refused or didn't confirm" critical={Boolean(summary&&(summary.failed+summary.uncertain))}/><OpsMetric label="Auto-funded today" value={summary?.autoToday??'—'} detail={summary?opsMoney(summary.autoTodayAmount)+' invoice value · '+summary.timeZone:'Count unavailable'}/></div>
      <div className="oc-tabs" role="tablist" aria-label="Funding lane">{lanes.map(([key,label])=><button className="oc-tab" role="tab" aria-selected={lane===key} key={key} disabled={loading||busy} onClick={()=>setLane(key)}>{label}<span>{summary?(key==='decision'?summary.approved:key==='suggestions'?summary.suggested:key==='exceptions'?summary.failed+summary.uncertain:summary.funded):'—'}</span></button>)}</div>
      <div className="oc-toolbar"><input type="search" aria-label="Search loaded funding decisions" placeholder="Search loaded invoices, clients, or reasons" value={query} onChange={e=>setQuery(e.target.value)}/><span className="oc-small oc-muted">{rows.length} matching loaded decisions · {opsMoney(rows.reduce((sum,r)=>sum+r.amount,0))} invoice value</span></div>
      <OpsPanel title={lanes.find(([key])=>key===lane)![1]} description={lane==='decision'?'A rule or limit held each one for a person. One click funds it.':lane==='suggestions'?'Clients on suggest-only: approving re-checks every rule first.':lane==='exceptions'?'FactorCloud refused or didn\'t confirm. Trying again re-checks every rule first.':'Funded, automatically or with a click.'}>
        {rows.length?<div className="oc-table-wrap"><table className="oc-table"><thead><tr><th>Invoice / client</th><th>Debtor</th><th>Status & reason</th><th className="num">Invoice value</th><th>Next action</th></tr></thead><tbody>{rows.map(run=><tr key={run.id}><td className="oc-identity"><strong>{run.invoiceNumber||run.factorCloudInvoiceId.slice(0,8)}</strong><small>{run.clientName||'Client not named'}</small></td><td>{run.debtorName?(run.debtorId?<a className="oc-link" href={'/ops/debtors?debtor='+encodeURIComponent(run.debtorId)}>{run.debtorName}</a>:run.debtorName):<span className="oc-muted">—</span>}</td><td><OpsStatus tone={unresolved(run)||run.state==='FAILED'?'bad':run.state==='FUNDED'?'good':run.state==='SUGGESTED'?'suggest':'info'}>{unresolved(run)?'Reconciliation required':runLabel(run)}</OpsStatus><div className="oc-reason">{run.reasons[0]||run.detail||'All recorded checks passed.'}</div></td><td className="num"><strong>{opsMoney(run.amount)}</strong></td><td>{unresolved(run)?<a className="oc-button" href="/ops/recovery">Open Recovery</a>:<button className="oc-button" disabled={busy} onClick={()=>{setAck(false);setSelected(run);}}>{run.state==='APPROVED'?'Review funding':heldForClick(run)?'Review & fund':run.state==='FUNDED'?'View record':'Review decision'}</button>}</td></tr>)}</tbody></table></div>:<OpsEmpty>{query?'No loaded decisions match this search.':'No records in this lane.'}</OpsEmpty>}
      </OpsPanel>
      {data.next&&<p><button className="oc-button" disabled={loading||busy} onClick={()=>void refresh(true)}>{loading?'Loading…':'Load more decisions'}</button></p>}
      <p className="oc-note">Amounts are invoice value; the advance paid out is set by the client's terms in FactorCloud.</p>
      {Boolean(summary?.review)&&<OpsNotice>{summary!.review} invoice{summary!.review===1?' is':'s are'} waiting on paperwork review before approval. <a href="/ops/reviews">Open Paperwork Review</a></OpsNotice>}
    </>}
    {selected&&<OpsDialog title={(selected.state==='APPROVED'||heldForClick(selected)?'Review funding · ':'Review decision · ')+(selected.invoiceNumber||selected.factorCloudInvoiceId.slice(0,8))} onClose={()=>{if(!busy)setSelected(null);}}><dl className="oc-facts"><div><dt>Client</dt><dd>{selected.clientName||'Not named'}</dd></div><div><dt>Invoice value</dt><dd>{opsMoney(selected.amount)}</dd></div><div><dt>Debtor</dt><dd>{selected.debtorName||'—'}</dd></div><div><dt>Payment type</dt><dd>{selected.paymentType||'Not recorded'}</dd></div><div><dt>Automation mode</dt><dd>{modeLabels[selected.mode as keyof typeof modeLabels]||selected.mode}</dd></div><div><dt>Recorded at</dt><dd>{opsTime(selected.createdAt)}</dd></div></dl><div className="oc-section-label">Rule by rule</div>{[...selected.rules].sort((a,b)=>rank(a.status)-rank(b.status)).map(rule=><div className="oc-check" key={rule.id}><OpsStatus tone={rule.status==='PASS'?'good':rule.status==='REVIEW'||rule.status==='UNKNOWN'?'bad':rule.status==='HOLD'?'warn':'neutral'}>{rule.status}</OpsStatus><strong>{rule.label}</strong><p>{rule.detail}</p></div>)}
      {selected.state==='APPROVED'&&<><div className="oc-section-label">What this click funds</div>{batch==='loading'?<p className="oc-note">Checking the FactorCloud funding batch…</p>:batch==='error'||!batch?<OpsNotice tone="warn">The FactorCloud funding batch couldn't be checked. Funding checks it again before any money moves.</OpsNotice>:<><p className="oc-note">FactorCloud pays whole batches. {batch.code?'Batch '+batch.code+' ':'This batch '}holds {batch.invoices.length} invoice{batch.invoices.length===1?'':'s'}{batch.invoices.length>1?'; all of them are funded together':''}.</p><div className="oc-table-wrap"><table className="oc-table"><tbody>{batch.invoices.map(i=><tr key={i.invoiceId}><td className="oc-identity"><strong>{i.invoiceNumber||i.invoiceId.slice(0,8)}</strong><small>{i.clientName||'—'}</small></td><td>{i.runId?(i.runId===selected.id?<OpsStatus tone="info">This invoice</OpsStatus>:<OpsStatus tone={i.outcome==='FUND'?'good':'warn'}>{i.outcome==='FUND'?'Passed every rule':'Held by a rule'}</OpsStatus>):<OpsStatus tone="warn">Approved outside the portal</OpsStatus>}</td><td className="num">{i.amount==null?'—':opsMoney(i.amount)}</td></tr>)}</tbody></table></div></>}</>}
      {selectedAction&&<><OpsNotice tone="warn">{selected.state==='APPROVED'?'Confirming funds the whole FactorCloud batch above.':heldForClick(selected)?'Approves the invoice in FactorCloud and funds it. If FactorCloud puts it in a batch with other invoices, it stops at approved so you can see the batch before paying it.':'Approval re-checks every rule first and funds it automatically if everything passes.'} The advance paid out is set by the client's terms in FactorCloud.</OpsNotice><label className="oc-rule-toggle"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} disabled={busy}/>I verified the financial details and understand this action.</label></>}
      {error&&<OpsNotice tone="bad">{error}</OpsNotice>}<div className="oc-actions"><button className="oc-button" disabled={busy} onClick={()=>setSelected(null)}>Close</button>{selectedAction&&<button className="oc-button primary" disabled={busy||!ack||!data?.canAct||batch==='loading'} onClick={()=>void act()}>{busy?'Working…':selected.state==='APPROVED'?(batch&&typeof batch==='object'&&batch.invoices.length>1?'Fund all '+batch.invoices.length:'Confirm funding'):heldForClick(selected)?'Approve & fund':'Confirm approval'}</button>}</div>{selectedAction&&!data?.canAct&&<p className="oc-note">Only a Factor Admin can execute this financial action.</p>}
    </OpsDialog>}
  </section></main>;
}

/** Rules that held or stopped the invoice come first, then the ones that passed. */
const rank=(status:string)=>({REVIEW:0,HOLD:1,UNKNOWN:2,PASS:3,SKIP:4} as Record<string,number>)[status]??5;
