'use client';
import {useEffect,useState} from 'react';
import {OpsSidebar} from '@/app/components/OpsSidebar';
import {OpsHeader,OpsPanel,OpsNotice,OpsStatus,OpsEmpty,OpsDialog,OpsSync,opsFetch,opsMoney} from '@/app/components/OpsUI';
import {clientExplanation,flaggedChecks} from '@/lib/override';
import {oldestFirst,waitsOnClient,waitLabel,type ReviewData,type ReviewRecord} from '@/lib/operations-view';
import {demoInBrowser} from '@/lib/demo';
import styles from './ReviewQueue.module.css';
type Lane='factor'|'client'|'answered'|'all';
type Decision='APPROVE'|'REQUEST_FIX'|'REJECT';
const laneNames:{key:Lane;title:string}[]=[{key:'factor',title:'With the factor'},{key:'client',title:'Waiting on client'},{key:'answered',title:'Client responded'},{key:'all',title:'All open'}];
function DocumentsPane({invoiceId,record,demo}:{invoiceId:string|null;record:ReviewRecord;demo:boolean}){
  const [state,setState]=useState<'loading'|'ready'|'none'|'demo'>(demo?'demo':invoiceId?'loading':'none'),[note,setNote]=useState('');
  useEffect(()=>{if(demo||!invoiceId)return;let live=true;fetch('/api/ops/invoices/'+encodeURIComponent(invoiceId)+'/documents?check=1',{cache:'no-store'}).then(async res=>{const body=await res.json().catch(()=>({}));if(!live)return;if(res.ok&&body.available)setState('ready');else if(body.demo)setState('demo');else{setState('none');setNote(body.error||'The documents could not be loaded from FactorCloud.');}}).catch(()=>{if(live){setState('none');setNote('The documents could not be loaded from FactorCloud.');}});return()=>{live=false;};},[invoiceId,demo]);
  if(state==='demo')return <DemoDocument record={record}/>;
  if(state==='loading')return <OpsEmpty>Loading the documents from FactorCloud…</OpsEmpty>;
  if(state==='none')return <OpsEmpty>{note||'No FactorCloud invoice is linked to this submission yet.'}</OpsEmpty>;
  const src='/api/ops/invoices/'+encodeURIComponent(invoiceId!)+'/documents';
  return <div className={styles.docPane}><iframe title={'Documents for '+(record.invoiceNumber||'this invoice')} src={src}/><a className="oc-link" href={src} target="_blank" rel="noreferrer">Open in a new tab ↗</a></div>;
}

/** Demo mode has no real paperwork: a sample invoice drawn from the record's own details. */
function DemoDocument({record}:{record:ReviewRecord}){
  const flagged=(record.checks||[]).flatMap(c=>c.comparisons||[]);
  return <div className={styles.demoDoc}><span className={styles.demoTag}>Demo document</span><div className={styles.docHead}><strong>INVOICE</strong><span>{record.invoiceNumber}</span></div><dl><div><dt>Invoice date</dt><dd>{record.invoiceDate||'—'}</dd></div><div><dt>Amount due</dt><dd>{record.invoiceAmount==null?'—':opsMoney(record.invoiceAmount)}</dd></div>{flagged.map((c,i)=><div key={i} className={styles.mark}><dt>{c.label}</dt><dd>{c.document}</dd></div>)}</dl><p className="oc-small oc-muted">With a FactorCloud connection this shows the invoice, BOL and POD exactly as they were sent in.</p></div>;
}

export default function PaperworkReview() {
  const [data,setData]=useState<ReviewData|null>(null),[selectedId,setSelectedId]=useState(''),[lane,setLane]=useState<Lane>('factor'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[decision,setDecision]=useState<Decision|null>(null),[note,setNote]=useState(''),[comparing,setComparing]=useState(false);
  async function load(force=false){setLoading(true);setError('');try{const body=await opsFetch<ReviewData>('/api/ops/reviews'+(force?'?refresh=1':''));setData(body);}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setLoading(false);}}
  useEffect(()=>{void load();const id=new URLSearchParams(window.location.search).get('review');if(id){setSelectedId(id);setLane('all');}},[]);
  const all=oldestFirst(data?.records||[]),matchesLane=(r:ReviewRecord,key:Lane)=>key==='all'||(key==='client'?waitsOnClient(r):key==='answered'?r.fix?.status==='DONE':!waitsOnClient(r));
  const client=(r:ReviewRecord)=>r.companyClientId?data?.clientNames[r.companyClientId]||'Client not named':'Client not named';
  const debtor=(r:ReviewRecord)=>r.companyDebtorId?data?.debtorNames[r.companyDebtorId]||'Debtor not named':'Debtor not named';
  const rows=all.filter(r=>matchesLane(r,lane)).filter(r=>([r.invoiceNumber,client(r),debtor(r),r.reason].join(' ')).toLowerCase().includes(query.toLowerCase()));
  const selected=rows.find(r=>(r.reviewId||r.id)===selectedId)||rows[0];
  const flagged=selected?flaggedChecks(selected.checks):[],explanation=selected?clientExplanation(selected.checks):null;
  async function save(){if(!selected?.reviewId||!decision)return;setBusy(true);setError('');try{const res=await fetch('/api/ops/reviews/'+encodeURIComponent(selected.reviewId),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,note:note.trim()||null})});const body=await res.json();if(!res.ok)throw new Error(body.error||'Could not record the review decision.');setMessage(decision==='APPROVE'?'Paperwork cleared. Approval remains pending.':decision==='REQUEST_FIX'?'Correction requested. The client is the next actor.':'Submission rejected.');setDecision(null);await load();if(body.factorCloud&&!body.factorCloud.ok)setError(body.factorCloud.detail||'Review was saved, but FactorCloud was not updated.');}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setBusy(false);}}
  return <main className="opsShell"><OpsSidebar active="reviews"/><section className="opsContent"><OpsHeader title="Paperwork Review" description="Resolve document exceptions before the separate approval decision." actions={<button className="oc-button" disabled={loading||busy} onClick={()=>void load(true)}>{loading?'Refreshing…':'Refresh'}</button>}/>
    {error&&<OpsNotice tone="bad">{error}</OpsNotice>}<OpsSync sync={data?.sync}/>{message&&<OpsNotice>{message}</OpsNotice>}{data?.source?.note&&<p className="oc-note">{data.source.note}</p>}
    <div className="oc-tabs" role="tablist" aria-label="Paperwork queue">{laneNames.map(item=><button className="oc-tab" role="tab" aria-selected={lane===item.key} key={item.key} onClick={()=>{setLane(item.key);setSelectedId('');}}>{item.title}<span>{all.filter(r=>matchesLane(r,item.key)).length}</span></button>)}</div>
    <div className="oc-toolbar"><input type="search" aria-label="Search paperwork exceptions" placeholder="Search invoice, client, debtor, or issue" value={query} onChange={e=>setQuery(e.target.value)}/><span className="oc-small oc-muted">{rows.length} exceptions · oldest first</span></div>
    {loading&&!data?<OpsEmpty>Loading paperwork exceptions…</OpsEmpty>:<div className="oc-split"><OpsPanel title="Exception queue" description="Select an invoice to compare the evidence.">{rows.length?<div className="oc-table-wrap"><table className="oc-table"><thead><tr><th>Invoice / client</th><th>Blocking issue</th><th>Waiting</th></tr></thead><tbody>{rows.map(r=><tr key={r.reviewId||r.id} className={selected===r?'selected':''}><td className="oc-identity"><button className="oc-link" aria-pressed={selected===r} onClick={()=>setSelectedId(r.reviewId||r.id)}>{r.invoiceNumber||r.id.slice(0,8)}</button><small>{client(r)}</small><small>{r.invoiceAmount==null?'Not available':opsMoney(r.invoiceAmount)} invoice value</small></td><td>{r.reason||'Paperwork requires review'}<div className="oc-reason">{waitsOnClient(r)?'Next: client':r.fix?.status==='DONE'?'Client responded · next: factor':'Next: factor operations'}</div></td><td>{waitLabel(r.createdAt)}</td></tr>)}</tbody></table></div>:<OpsEmpty>{error?'Queue data unavailable.':query?'No exceptions match this search.':'No paperwork exceptions in this queue.'}</OpsEmpty>}</OpsPanel>
    <OpsPanel title="Selected exception">{selected?<div className="oc-body"><div className="oc-detail-title"><div><h2>{selected.invoiceNumber||selected.id.slice(0,8)}</h2><p>{client(selected)} → {debtor(selected)}</p></div><OpsStatus tone={waitsOnClient(selected)?'neutral':'warn'}>{waitsOnClient(selected)?'Waiting on client':'Factor review'}</OpsStatus></div><dl className="oc-facts"><div><dt>Invoice value</dt><dd>{selected.invoiceAmount==null?'Not available':opsMoney(selected.invoiceAmount)}</dd></div><div><dt>Invoice date</dt><dd>{selected.invoiceDate||'Not available'}</dd></div><div><dt>Next actor</dt><dd>{waitsOnClient(selected)?'Client':'Factor operations'}</dd></div></dl><OpsNotice tone="warn">{selected.reason||'Paperwork requires review.'}</OpsNotice>
      {explanation&&<OpsNotice><strong>Client explanation</strong><p>{explanation}</p></OpsNotice>}
      {selected.fix&&<div className="oc-check"><strong>Correction requested</strong><p>{selected.fix.message}</p>{selected.fix.status==='DONE'&&<><strong>Client response</strong><p>{selected.fix.responseNote||'The requested files were uploaded.'}</p></>}</div>}
      <div className="oc-actions"><button className="oc-button primary" onClick={()=>setComparing(true)}>Compare with documents</button></div><div className="oc-section-label">Original comparison evidence</div>{flagged.length?flagged.map(check=><div className="oc-check" key={check.id}><OpsStatus tone={check.status==='FAIL'?'bad':'warn'}>{check.status}</OpsStatus><strong>{check.label}</strong><p>{check.message}</p>{check.comparisons?.map((comparison,i)=><div className="oc-small" key={i}><strong>{comparison.label}</strong><span>{comparison.document}{comparison.other?' vs '+comparison.other:''}</span></div>)}</div>):<p className="oc-small oc-muted">Detailed checks were not supplied for this record.</p>}
      {selected.submissionId&&<p><a className="oc-link" href={'/ops/submissions/'+encodeURIComponent(selected.submissionId)}>Open submission and source documents →</a></p>}
      <OpsNotice>Clearing paperwork accepts the document review. It does not approve or fund the invoice.</OpsNotice>
      {selected.reviewId?<div className="oc-actions"><button className="oc-button primary" disabled={busy} onClick={()=>{setNote('');setDecision('APPROVE');}}>Clear paperwork</button>{!waitsOnClient(selected)&&<button className="oc-button" disabled={busy} onClick={()=>{setNote('');setDecision('REQUEST_FIX');}}>Request correction</button>}<button className="oc-button danger" disabled={busy} onClick={()=>{setNote('');setDecision('REJECT');}}>Reject submission</button></div>:<p className="oc-note">Record the decision in FactorCloud for this setup.</p>}
    </div>:<OpsEmpty>Select an exception to inspect its evidence.</OpsEmpty>}</OpsPanel></div>}
    {comparing&&selected&&<OpsDialog wide title={'Compare · '+(selected.invoiceNumber||selected.id.slice(0,8))} onClose={()=>setComparing(false)}><div className={styles.compare}><div className={styles.compareChecks}><p className="oc-small oc-muted">{client(selected)} → {debtor(selected)} · {selected.invoiceAmount==null?'amount not available':opsMoney(selected.invoiceAmount)}</p>{explanation&&<OpsNotice><strong>Client explanation</strong><p>{explanation}</p></OpsNotice>}{flagged.length?flagged.map(check=><div className="oc-check" key={check.id}><OpsStatus tone={check.status==='FAIL'?'bad':'warn'}>{check.status}</OpsStatus><strong>{check.label}</strong><p>{check.message}</p>{check.comparisons?.map((comparison,i)=><div className="oc-small" key={i}><strong>{comparison.label}</strong><span>{comparison.document}{comparison.other?' vs '+comparison.other:''}</span></div>)}</div>):<p className="oc-small oc-muted">Detailed checks were not supplied for this record.</p>}{selected.reviewId&&<div className="oc-actions"><button className="oc-button primary" disabled={busy} onClick={()=>{setComparing(false);setNote('');setDecision('APPROVE');}}>Clear paperwork</button>{!waitsOnClient(selected)&&<button className="oc-button" disabled={busy} onClick={()=>{setComparing(false);setNote('');setDecision('REQUEST_FIX');}}>Request correction</button>}<button className="oc-button danger" disabled={busy} onClick={()=>{setComparing(false);setNote('');setDecision('REJECT');}}>Reject</button></div>}</div><DocumentsPane invoiceId={selected.submissionId&&selected.id===selected.submissionId?null:selected.id} record={selected} demo={demoInBrowser()}/></div></OpsDialog>}
    {decision&&selected&&<OpsDialog title={decision==='APPROVE'?'Clear paperwork':decision==='REQUEST_FIX'?'Request a correction':'Reject submission'} onClose={()=>{if(!busy)setDecision(null);}}><p>{decision==='APPROVE'?'Accept the paperwork review for '+(selected.invoiceNumber||'this invoice')+'. Approval and funding remain separate decisions.':decision==='REQUEST_FIX'?'Tell the client which document or field needs correction. This records a correction task in the existing client workflow.':'Record why this submission cannot continue.'}</p><div className="oc-form"><label>Audit note {decision==='APPROVE'?'(optional)':'(required)'}<textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} disabled={busy}/></label></div>{error&&<OpsNotice tone="bad">{error}</OpsNotice>}<div className="oc-actions"><button className="oc-button" disabled={busy} onClick={()=>setDecision(null)}>Cancel</button><button className={'oc-button '+(decision==='REJECT'?'danger':'primary')} disabled={busy||(decision!=='APPROVE'&&!note.trim())} onClick={()=>void save()}>{busy?'Saving…':decision==='APPROVE'?'Confirm paperwork clearance':decision==='REQUEST_FIX'?'Record correction request':'Confirm rejection'}</button></div></OpsDialog>}
  </section></main>;
}
