'use client';
import {useEffect,useState} from 'react';
import {OpsSidebar} from '@/app/components/OpsSidebar';
import {OpsHeader,OpsPanel,OpsMetric,OpsNotice,OpsStatus,OpsEmpty,OpsIcon,opsFetch,opsMoney,opsTime} from '@/app/components/OpsUI';
import {DashboardSkeleton} from '@/app/components/CommandCharts';
import {modeLabels,runLabel,waitsOnClient,oldestFirst,waitLabel,type FundingData,type ReviewData} from '@/lib/operations-view';
type RecoveryData={items:{id:string;kind:string;invoice_number:string|null;detail:string;created_at:string}[];editable:boolean;note?:string};
export default function Overview() {
  const [funding,setFunding]=useState<FundingData|null>(null),[activity,setActivity]=useState<FundingData|null>(null),[reviews,setReviews]=useState<ReviewData|null>(null),[recovery,setRecovery]=useState<RecoveryData|null>(null);
  const [loading,setLoading]=useState(true),[errors,setErrors]=useState<string[]>([]);
  async function load(){setLoading(true);const results=await Promise.allSettled([opsFetch<FundingData>('/api/ops/funding?lane=decision'),opsFetch<FundingData>('/api/ops/funding'),opsFetch<ReviewData>('/api/ops/reviews'),opsFetch<RecoveryData>('/api/ops/recovery')]);const notes:string[]=[];results.forEach((r,i)=>{if(r.status==='fulfilled'){if(i===0)setFunding(r.value as FundingData);if(i===1)setActivity(r.value as FundingData);if(i===2)setReviews(r.value as ReviewData);if(i===3)setRecovery(r.value as RecoveryData);}else{notes.push(['Funding','Recent activity','Paperwork review','Recovery'][i]+': '+String(r.reason?.message||r.reason));if(i===0)setFunding(null);if(i===1)setActivity(null);if(i===2)setReviews(null);if(i===3)setRecovery(null);}});setErrors(notes);setLoading(false);}
  useEffect(()=>{void load();},[]);
  const ready=funding?.available?funding.runs:[],summary=funding?.available?funding.summary:null;
  const rows=oldestFirst(reviews?.records||[]),factorRows=rows.filter(r=>!waitsOnClient(r)),clientCount=rows.length-factorRows.length;
  const recoveryAvailable=Boolean(recovery&&!recovery.note),recoveryCount=recoveryAvailable?recovery!.items.length:null;
  return <main className="opsShell"><OpsSidebar active="overview"/><section className="opsContent">
    <OpsHeader title="Overview" description="Prioritize exceptions. Keep invoices moving." actions={<><button className="oc-button" onClick={()=>void load()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button><a className="oc-button primary" href="/ops/funding">Review funding <OpsIcon name="arrow"/></a></>}/>
    {errors.map(error=><OpsNotice tone="bad" key={error}>{error}</OpsNotice>)}
    {recoveryCount!=null&&recoveryCount>0&&<div className="oc-alert"><div><strong>{recoveryCount} operation{recoveryCount===1?'':'s'} need reconciliation</strong><p>Verify the remote result before another approval or funding attempt.</p></div><a className="oc-button" href="/ops/recovery">Open Recovery</a></div>}
    {loading&&!reviews&&!funding?<DashboardSkeleton metrics={4}/>:<>
      <div className="oc-metrics">
        <OpsMetric label="Paperwork exceptions" value={reviews?rows.length:'—'} detail={reviews?factorRows.length+' with factor · '+clientCount+' with client':'Review data unavailable'} href="/ops/reviews"/>
        <OpsMetric label="Approved · needs funding" value={summary?.approved??'—'} detail={summary?opsMoney(summary.approvedAmount)+' invoice value':'Funding data unavailable'} href="/ops/funding"/>
        <OpsMetric label="Auto-funded today" value={summary?.autoToday??'—'} detail={summary?opsMoney(summary.autoTodayAmount)+' invoice value · '+summary.timeZone:'Funding data unavailable'} href="/ops/funding?lane=funded"/>
        <OpsMetric label="Open reconciliation" value={recoveryCount??'—'} detail={recoveryCount==null?'Recovery data unavailable':'Verify uncertain or incomplete operations'} href="/ops/recovery" critical={Boolean(recoveryCount)}/>
      </div>
      <div className="oc-grid"><div className="oc-stack">
        {(!funding?.available||!ready.length)&&<Paperwork rows={factorRows} data={reviews}/>}
        <OpsPanel title="Funding queue" description="Approved invoices first. Review the decision before moving money." action={<a className="oc-link" href="/ops/funding">All funding →</a>}>
          {!funding?.available?<OpsEmpty><strong>Funding automation unavailable</strong><p>{funding?.note||'Could not load the funding engine.'}</p></OpsEmpty>:!ready.length?<OpsEmpty>No approved invoices are waiting for a funding decision.</OpsEmpty>:<div className="oc-table-wrap"><table className="oc-table"><thead><tr><th>Invoice / client</th><th>Decision & next step</th><th className="num">Invoice value</th><th>Action</th></tr></thead><tbody>{ready.slice(0,5).map(run=><tr key={run.id}><td className="oc-identity"><strong>{run.invoiceNumber||run.factorCloudInvoiceId.slice(0,8)}</strong><small>{run.clientName||'Client not named'}</small></td><td><OpsStatus tone="info">Approved</OpsStatus><div className="oc-reason">{run.reasons[0]||run.detail||'Funding requires a person.'}</div></td><td className="num"><strong>{opsMoney(run.amount)}</strong></td><td><a className="oc-button" href={'/ops/funding?run='+encodeURIComponent(run.id)}>Review funding</a></td></tr>)}</tbody></table></div>}
        </OpsPanel>
        {funding?.available&&ready.length>0&&<Paperwork rows={factorRows} data={reviews}/>}
      </div><aside className="oc-stack">
        <OpsPanel title="Automation control"><div className="oc-body"><h3><OpsIcon name="rules"/> {funding?.available?modeLabels[funding.mode]:'Unavailable'}</h3><p className="oc-small oc-muted">{funding?.available?(funding.mode==='approve'?'Approvals automated. Funding requires a person.':funding.mode==='fund'?'Approval and funding may run within configured rules and caps.':funding.mode==='suggest'?'Suggestions only. People control the financial steps.':'The engine is off.'):funding?.note||'Engine data could not be read.'}</p><dl className="oc-facts"><div><dt>Approval gate</dt><dd>{!funding?.available?'Unavailable':funding.mode==='approve'||funding.mode==='fund'?'Automatic':'Human decision'}</dd></div><div><dt>Funding gate</dt><dd>{!funding?.available?'Unavailable':funding.mode==='fund'?'Automatic within limits':'Human decision'}</dd></div><div><dt>Approval failures</dt><dd>{summary?.failed??'—'}</dd></div><div><dt>Engine health</dt><dd>Not assessed</dd></div></dl><p><a className="oc-link" href="/ops/rules">View automation rules →</a></p></div></OpsPanel>
        <OpsPanel title="Recent activity">{activity?.available&&activity.runs.length?activity.runs.slice(0,5).map(run=><div className="oc-activity" key={run.id}><OpsIcon name={run.state==='FUNDING'||run.state==='FAILED'?'recovery':'check'}/><div><strong>{run.invoiceNumber||run.factorCloudInvoiceId.slice(0,8)} · {runLabel(run)}</strong><small>{run.clientName||run.detail||'FactorCloud invoice'}</small></div><time>{opsTime(run.fundedAt||run.createdAt)}</time></div>):<OpsEmpty>{activity?.available?'No engine activity recorded.':'Activity data unavailable.'}</OpsEmpty>}</OpsPanel>
      </aside></div><div className="oc-toolbar" style={{marginTop:16}}><span className="oc-note">Queue counts cover all engine runs. Amounts are invoice face value.</span><a className="oc-link" href="/ops/reports">Portfolio reports →</a></div>
    </>}
  </section></main>;
}
function Paperwork({rows,data}:{rows:ReviewData['records'];data:ReviewData|null}) {return <OpsPanel title="Paperwork review" description="Oldest work with the factor first." action={<a className="oc-link" href="/ops/reviews">All exceptions →</a>}>{!data?<OpsEmpty>Review data unavailable.</OpsEmpty>:!rows.length?<OpsEmpty>No paperwork exceptions currently require the factor.</OpsEmpty>:<div className="oc-table-wrap"><table className="oc-table"><thead><tr><th>Invoice / client</th><th>Exception</th><th>Next actor</th><th>Waiting</th></tr></thead><tbody>{rows.slice(0,4).map(row=><tr key={row.reviewId||row.id}><td className="oc-identity"><a className="oc-link" href={'/ops/reviews?review='+encodeURIComponent(row.reviewId||row.id)}>{row.invoiceNumber||row.id.slice(0,8)}</a><small>{row.companyClientId?data.clientNames[row.companyClientId]||'Client not named':'Client not named'}</small></td><td>{row.reason||'Paperwork requires review'}</td><td>Factor operations</td><td>{waitLabel(row.createdAt)}</td></tr>)}</tbody></table></div>}</OpsPanel>;}
