'use client';
import {useEffect,useState} from 'react';
import {OpsSidebar} from '@/app/components/OpsSidebar';
import {DemoBadge} from '@/app/components/DemoBadge';
import {OpsHeader,OpsPanel,OpsMetric,OpsNotice,OpsStatus,OpsEmpty,OpsDialog,opsFetch,opsMoney} from '@/app/components/OpsUI';
import type {DebtorSummary} from '@/lib/debtors';
type Data={today:string;debtors:DebtorSummary[];complete:boolean;incompleteReason:string|null;demo?:boolean};
function signals(d:DebtorSummary){const flags:{label:string;tone:'bad'|'warn'}[]=[];if(d.share>=.15)flags.push({label:'15%+ exposure',tone:'warn'});if(d.buckets[3]>0)flags.push({label:'90+ invoice age',tone:'bad'});else if((d.oldestOpenDays||0)>60)flags.push({label:'60+ invoice age',tone:'warn'});if((d.daysToPay||0)>55&&d.paidCount>=2)flags.push({label:'Slow payer',tone:'warn'});if(d.disputedCount>0)flags.push({label:d.disputedCount+' disputed',tone:'bad'});return flags;}
export default function Debtors(){
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[all,setAll]=useState(false),[sort,setSort]=useState('risk'),[selected,setSelected]=useState<DebtorSummary|null>(null);
  async function load(){setLoading(true);setError('');try{setData(await opsFetch<Data>('/api/ops/debtors'));}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const debtors=data?.debtors||[],attention=debtors.filter(d=>signals(d).length>0);
  const rows=(all?debtors:attention).filter(d=>(d.name+' '+(d.topClient||'')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='exposure'?b.openBalance-a.openBalance:sort==='age'?(b.oldestOpenDays||0)-(a.oldestOpenDays||0):signals(b).length-signals(a).length||b.openBalance-a.openBalance);
  return <main className="opsShell"><OpsSidebar active="debtors"/><section className="opsContent"><OpsHeader title="Debtors" description="Inspect payer exposure and behavior before taking more risk." actions={<button className="oc-button" disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh'}</button>}>{data?.demo&&<DemoBadge/>}</OpsHeader>
    {error&&<OpsNotice tone="bad">{error}</OpsNotice>}{data&&!data.complete&&<OpsNotice tone="warn"><strong>Partial portfolio.</strong> {data.incompleteReason}</OpsNotice>}
    {!data?<OpsEmpty>{loading?'Loading debtor risk…':'Debtor data unavailable.'}</OpsEmpty>:<>
      <div className="oc-metrics"><OpsMetric label="Open funded exposure" value={opsMoney(debtors.reduce((s,d)=>s+d.openBalance,0))} detail={debtors.filter(d=>d.openBalance>0).length+' payers with open exposure'}/><OpsMetric label="Needs attention" value={attention.length} detail="Payers with one or more watch flags"/><OpsMetric label="Balance aged 90+ days" value={opsMoney(debtors.reduce((s,d)=>s+d.buckets[3],0))} detail="Age from invoice date"/><OpsMetric label="Purchase eligibility" value="Unknown" detail="Credit and No Buy not supplied here"/></div>
      <div className="oc-tabs" role="tablist" aria-label="Debtor watch"><button className="oc-tab" role="tab" aria-selected={!all} onClick={()=>setAll(false)}>Needs attention<span>{attention.length}</span></button><button className="oc-tab" role="tab" aria-selected={all} onClick={()=>setAll(true)}>All debtors<span>{debtors.length}</span></button></div>
      <div className="oc-toolbar"><input type="search" aria-label="Search debtors" placeholder="Search payer or exposed client" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Sort debtor table" value={sort} onChange={e=>setSort(e.target.value)}><option value="risk">Watch flags first</option><option value="exposure">Largest exposure</option><option value="age">Oldest invoice</option><option value="name">Payer name</option></select></div>
      <OpsPanel title="Payer risk watch" description="Watch signals supply context; they do not establish purchase eligibility.">{rows.length?<div className="oc-table-wrap"><table className="oc-table"><thead><tr><th>Payer / clients exposed</th><th className="num">Open exposure</th><th className="num">Portfolio share</th><th>Watch signals</th><th className="num">90+ age balance</th><th className="num">Avg days to pay</th><th className="num">Oldest invoice</th></tr></thead><tbody>{rows.map(d=><tr key={d.debtorId}><td className="oc-identity"><button className="oc-link" onClick={()=>setSelected(d)}>{d.name}</button><small>{d.clientCount} exposed clients · {d.topClient||'No exposed client'}</small></td><td className="num"><strong>{opsMoney(d.openBalance)}</strong></td><td className="num">{(d.share*100).toFixed(1)}%</td><td><div className="oc-actions">{signals(d).length?signals(d).map(flag=><OpsStatus key={flag.label} tone={flag.tone}>{flag.label}</OpsStatus>):<OpsStatus>No listed risk flags</OpsStatus>}</div></td><td className="num">{opsMoney(d.buckets[3])}</td><td className="num">{d.daysToPay==null?'—':Math.round(d.daysToPay)+'d'}<div className="oc-reason">{d.paidCount} paid invoices</div></td><td className="num">{d.oldestOpenDays==null?'—':d.oldestOpenDays+'d'}</td></tr>)}</tbody></table></div>:<OpsEmpty>{query?'No matching payers.':'No payers in this view.'}</OpsEmpty>}</OpsPanel>
      <p className="oc-note">Watch policy: 15%+ of portfolio exposure, 90+ invoice age (or oldest invoice over 60 days), average payment time over 55 days with at least two paid invoices, or disputed invoices. These are watch thresholds, separate from configurable funding rules. Payment averages use paid invoices from the last 180 days.</p>
    </>}
    {selected&&<OpsDialog title={selected.name} onClose={()=>setSelected(null)}><dl className="oc-facts"><div><dt>Open funded exposure</dt><dd>{opsMoney(selected.openBalance)}</dd></div><div><dt>Share of portfolio exposure</dt><dd>{(selected.share*100).toFixed(1)}%</dd></div><div><dt>Credit limit / headroom</dt><dd>Not supplied in this view</dd></div><div><dt>No Buy / purchase eligibility</dt><dd>Not supplied in this view</dd></div><div><dt>Average payment time · 180d cohort</dt><dd>{selected.daysToPay==null?'Unavailable':Math.round(selected.daysToPay)+' days · '+selected.paidCount+' invoices'}</dd></div><div><dt>Clients exposed</dt><dd>{selected.clientCount}</dd></div><div><dt>Largest exposed client</dt><dd>{selected.topClient||'Not available'}</dd></div><div><dt>Invoice value · 90d</dt><dd>{opsMoney(selected.recentVolume)}</dd></div></dl><div className="oc-section-label">Open balance by invoice age</div>{selected.buckets.map((value,i)=><div className="oc-figure-row" key={i}><span>{['0–30d','31–60d','61–90d','90+d'][i]}</span><div className="oc-bar"><i style={{width:(selected.openBalance?value/selected.openBalance*100:0)+'%'}}/></div><strong className="oc-num">{opsMoney(value)}</strong></div>)}<OpsNotice tone="warn">No listed watch flags does not establish purchase eligibility. Confirm current credit and No Buy at the correct client/debtor scope.</OpsNotice><div className="oc-actions"><button className="oc-button" onClick={()=>setSelected(null)}>Close</button></div></OpsDialog>}
  </section></main>;
}
