'use client';
import {useEffect,useState} from 'react';
import {OpsSidebar} from '@/app/components/OpsSidebar';
import {DemoBadge} from '@/app/components/DemoBadge';
import {OpsHeader,OpsPanel,OpsMetric,OpsNotice,OpsStatus,OpsEmpty,OpsDialog,opsFetch,opsMoney} from '@/app/components/OpsUI';
import type {DebtorSummary} from '@/lib/debtors';
import type {FundingData} from '@/lib/operations-view';
import type {EngineRun} from '@/lib/funding-engine';
const DEBTOR_RULES=['credit-limit','slow-debtor','concentration','new-debtor','no-buy'];
/** Invoices the automation is holding because of a rule about the debtor. */
function debtorHolds(runs:EngineRun[]){const out=new Map<string,EngineRun[]>();for(const r of runs){if(!r.debtorId||!(r.state==='APPROVED'||r.state==='SUGGESTED'||r.state==='REVIEW'))continue;if(!r.rules.some(x=>DEBTOR_RULES.includes(x.id)&&(x.status==='HOLD'||x.status==='REVIEW')))continue;out.set(r.debtorId,[...(out.get(r.debtorId)||[]),r]);}return out;}
type Data={today:string;debtors:DebtorSummary[];complete:boolean;incompleteReason:string|null;demo?:boolean};
function signals(d:DebtorSummary){const flags:{label:string;tone:'bad'|'warn'}[]=[];if(d.share>=.15)flags.push({label:'15%+ exposure',tone:'warn'});if(d.buckets[3]>0)flags.push({label:'90+ invoice age',tone:'bad'});else if((d.oldestOpenDays||0)>60)flags.push({label:'60+ invoice age',tone:'warn'});if((d.daysToPay||0)>55&&d.paidCount>=2)flags.push({label:'Slow payer',tone:'warn'});if(d.disputedCount>0)flags.push({label:d.disputedCount+' disputed',tone:'bad'});return flags;}
export default function Debtors(){
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[all,setAll]=useState(false),[sort,setSort]=useState('risk'),[selected,setSelected]=useState<DebtorSummary|null>(null),[funding,setFunding]=useState<FundingData|null>(null);
  async function load(){setLoading(true);setError('');opsFetch<FundingData>('/api/ops/funding').then(setFunding).catch(()=>setFunding(null));try{const body=await opsFetch<Data>('/api/ops/debtors');setData(body);const params=new URLSearchParams(window.location.search),id=params.get('debtor');if(id){const d=body.debtors.find(x=>x.debtorId===id);if(d){setSelected(d);setAll(true);}}}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const holds=debtorHolds(funding?.available?funding.runs:[]),held=(d:DebtorSummary)=>holds.get(d.debtorId)||[];
  const debtors=data?.debtors||[],attention=debtors.filter(d=>signals(d).length>0||held(d).length>0);
  const rows=(all?debtors:attention).filter(d=>(d.name+' '+(d.topClient||'')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='exposure'?b.openBalance-a.openBalance:sort==='age'?(b.oldestOpenDays||0)-(a.oldestOpenDays||0):held(b).length-held(a).length||signals(b).length-signals(a).length||b.openBalance-a.openBalance);
  return <main className="opsShell"><OpsSidebar active="debtors"/><section className="opsContent"><OpsHeader title="Debtors" description="Who owes you, how they pay, and which invoices the automation is holding because of them." actions={<button className="oc-button" disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh'}</button>}>{data?.demo&&<DemoBadge/>}</OpsHeader>
    {error&&<OpsNotice tone="bad">{error}</OpsNotice>}{data&&!data.complete&&<OpsNotice tone="warn"><strong>Partial portfolio.</strong> {data.incompleteReason}</OpsNotice>}
    {!data?<OpsEmpty>{loading?'Loading debtor risk…':'Debtor data unavailable.'}</OpsEmpty>:<>
      <div className="oc-metrics"><OpsMetric label="Open funded exposure" value={opsMoney(debtors.reduce((s,d)=>s+d.openBalance,0))} detail={debtors.filter(d=>d.openBalance>0).length+' payers with open exposure'}/><OpsMetric label="Needs attention" value={attention.length} detail="Payers with one or more watch flags"/><OpsMetric label="Balance aged 90+ days" value={opsMoney(debtors.reduce((s,d)=>s+d.buckets[3],0))} detail="Age from invoice date"/><OpsMetric label="Held by debtor rules" value={[...holds.values()].reduce((t,r)=>t+r.length,0)} detail={holds.size+" debtors · credit, payment speed or concentration"} href="/ops/funding?lane=decision"/></div>
      <div className="oc-tabs" role="tablist" aria-label="Debtor watch"><button className="oc-tab" role="tab" aria-selected={!all} onClick={()=>setAll(false)}>Needs attention<span>{attention.length}</span></button><button className="oc-tab" role="tab" aria-selected={all} onClick={()=>setAll(true)}>All debtors<span>{debtors.length}</span></button></div>
      <div className="oc-toolbar"><input type="search" aria-label="Search debtors" placeholder="Search payer or exposed client" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Sort debtor table" value={sort} onChange={e=>setSort(e.target.value)}><option value="risk">Watch flags first</option><option value="exposure">Largest exposure</option><option value="age">Oldest invoice</option><option value="name">Payer name</option></select></div>
      <OpsPanel title="Payer risk watch" description="Warning signs on each payer, plus invoices the automation is holding because of them.">{rows.length?<div className="oc-table-wrap"><table className="oc-table"><thead><tr><th>Payer / clients exposed</th><th className="num">Open exposure</th><th className="num">Portfolio share</th><th>Watch signals</th><th className="num">90+ age balance</th><th className="num">Avg days to pay</th><th className="num">Oldest invoice</th></tr></thead><tbody>{rows.map(d=><tr key={d.debtorId}><td className="oc-identity"><button className="oc-link" onClick={()=>setSelected(d)}>{d.name}</button><small>{d.clientCount} exposed clients · {d.topClient||'No exposed client'}</small></td><td className="num"><strong>{opsMoney(d.openBalance)}</strong></td><td className="num">{(d.share*100).toFixed(1)}%</td><td><div className="oc-actions">{held(d).length>0&&<OpsStatus tone="info">{held(d).length} held by automation</OpsStatus>}{signals(d).length?signals(d).map(flag=><OpsStatus key={flag.label} tone={flag.tone}>{flag.label}</OpsStatus>):!held(d).length&&<OpsStatus>No warning signs</OpsStatus>}</div></td><td className="num">{opsMoney(d.buckets[3])}</td><td className="num">{d.daysToPay==null?'—':Math.round(d.daysToPay)+'d'}<div className="oc-reason">{d.paidCount} paid invoices</div></td><td className="num">{d.oldestOpenDays==null?'—':d.oldestOpenDays+'d'}</td></tr>)}</tbody></table></div>:<OpsEmpty>{query?'No matching payers.':'No payers in this view.'}</OpsEmpty>}</OpsPanel>
      <p className="oc-note">Warning signs: 15%+ of portfolio exposure, invoices over 90 days old (or the oldest over 60), paying in more than 55 days on average (paid invoices, last 180 days), or disputed invoices. Holds come from the Automation Rules.</p>
    </>}
    {selected&&<OpsDialog title={selected.name} onClose={()=>setSelected(null)}><dl className="oc-facts"><div><dt>Open funded exposure</dt><dd>{opsMoney(selected.openBalance)}</dd></div><div><dt>Share of portfolio exposure</dt><dd>{(selected.share*100).toFixed(1)}%</dd></div><div><dt>Average payment time · 180d cohort</dt><dd>{selected.daysToPay==null?'Unavailable':Math.round(selected.daysToPay)+' days · '+selected.paidCount+' invoices'}</dd></div><div><dt>Clients exposed</dt><dd>{selected.clientCount}</dd></div><div><dt>Largest exposed client</dt><dd>{selected.topClient||'Not available'}</dd></div><div><dt>Invoice value · 90d</dt><dd>{opsMoney(selected.recentVolume)}</dd></div></dl><div className="oc-section-label">Open balance by invoice age</div>{selected.buckets.map((value,i)=><div className="oc-figure-row" key={i}><span>{['0–30d','31–60d','61–90d','90+d'][i]}</span><div className="oc-bar"><i style={{width:(selected.openBalance?value/selected.openBalance*100:0)+'%'}}/></div><strong className="oc-num">{opsMoney(value)}</strong></div>)}{held(selected).length>0&&<><div className="oc-section-label">Held by the automation</div>{held(selected).map(r=><div className="oc-check" key={r.id}><OpsStatus tone="info">Held</OpsStatus><strong><a className="oc-link" href={'/ops/funding?lane='+(r.state==='SUGGESTED'?'suggestions':r.state==='REVIEW'?'review':'decision')+'&run='+encodeURIComponent(r.id)}>{r.invoiceNumber||r.factorCloudInvoiceId.slice(0,8)}</a> · {r.clientName} · {opsMoney(r.amount)}</strong><p>{r.rules.filter(x=>DEBTOR_RULES.includes(x.id)&&(x.status==='HOLD'||x.status==='REVIEW')).map(x=>x.detail).join(' ')}</p></div>)}</>}<div className="oc-actions"><button className="oc-button" onClick={()=>setSelected(null)}>Close</button></div></OpsDialog>}
  </section></main>;
}
